- addins/Cake.Issues.DocFx.yml
- addins/Cake.Issues.EsLint.yml
- addins/Cake.Issues.InspectCode.yml
- addins/Cake.Issues.Markdownlint.yml
- addins/Cake.Issues.MsBuild.yml
- addins/Cake.Issues.PullRequests.Tfs.yml
- input/docs/overview/release-notes/index.cshtml
> Fix release note links

- input/docs/issue-providers/docfx/requirements.md
- input/docs/issue-providers/eslint/requirements.md
- input/docs/issue-providers/inspectcode/requirements.md
- input/docs/issue-providers/markdownlint/requirements.md
- input/docs/issue-providers/msbuild/requirements.md
- input/docs/overview/requirements.md
- input/docs/pull-request-systems/tfs/requirements.md
- input/docs/report-formats/html/requirements.md
Update requirement to Cake 0.22.0
Fixes #6
> Update requirement to Cake 0.22.0

- addins/Cake.Issues.DocFx.yml
- addins/Cake.Issues.EsLint.yml
- addins/Cake.Issues.InspectCode.yml
- addins/Cake.Issues.Markdownlint.yml
- addins/Cake.Issues.MsBuild.yml
- addins/Cake.Issues.PullRequests.Tfs.yml
- addins/Cake.Issues.PullRequests.yml
- addins/Cake.Issues.Testing.yml
Use stable versions of released addins
> Use stable versions

- input/docs/issue-providers/docfx/examples.md
- input/docs/usage/reading-issues/basic-usage.md
> Improve usage examples

- input/docs/issue-providers/inspectcode/examples.md
Add InspectCode issue provider example
Fixes #4
> (GH-4)  Add InspectCode issue provider example

- input/docs/issue-providers/msbuild/examples.md
Add MsBuild issue provider example
Fixes #5
> (GH-5) Add MsBuild issue provider example

- input/docs/overview/features.md
Improve description of core features
> Improve description of core features

- input/docs/issue-providers/docfx/features.md
- input/docs/issue-providers/eslint/features.md
- input/docs/issue-providers/inspectcode/features.md
- input/docs/issue-providers/markdownlint/features.md
- input/docs/issue-providers/msbuild/features.md
Add documentation about supported comment format for each issue provider
Fixes #12
> (GH-12) Add documentation about supported comment format

- input/docs/report-formats/generic/index.cshtml
Fix title for generic report format
> Fix title for generic report format

- build.cake
Fix version of Cake.Yaml addin to be compatible with Cake.Wyam.Recipe
> Fix version of Cake.Yaml addin

- README.md
Was just reading through the README and noticed this.
> Resolve minor grammatical error

- input/docs/issue-providers/docfx/features.md
- input/docs/issue-providers/eslint/features.md
- input/docs/issue-providers/inspectcode/features.md
- input/docs/issue-providers/markdownlint/features.md
- input/docs/issue-providers/msbuild/features.md
Document the properties set on `IIssue` for each issue provider
Fixes #9
> (GH-9) Document properties set on IIssue for each issue provider

- input/docs/contributing/how-to-build.md
- input/docs/contributing/how-to-contribute.md
- input/docs/contributing/how-to-release.md
- input/docs/contributing/index.cshtml
Add information how to contribute
Fixes #11
> (GH-11) Add information how to contribute

- input/docs/report-formats/generic/examples.md
Add example how to use custom report template
Fixes #10
> (GH-10) Add example how to use custom template

- build.cake
- tools/packages.config
> Update to Cake 0.25.0

- input/docs/report-formats/generic/examples.md
Update imported assemblies for Cake.Issues.Reporting.Generic
> Update imported assemblies for Cake.Issues.Reporting.Generic

- input/docs/report-formats/generic/examples.md
Add note about inclusion of custom templates
> Add note about inclusion of custom templates

- input/docs/issue-providers/docfx/requirements.md
- input/docs/issue-providers/eslint/requirements.md
- input/docs/issue-providers/inspectcode/requirements.md
- input/docs/issue-providers/markdownlint/requirements.md
- input/docs/issue-providers/msbuild/requirements.md
- input/docs/overview/requirements.md
- input/docs/pull-request-systems/tfs/requirements.md
- input/docs/report-formats/generic/requirements.md
Link requirements to release notes which are always up to date for all versions.
> Link requirements to release notes

- input/docs/report-formats/generic/examples.md
Update documentation of loaded assemblies
> System.Core asembly is loaded in the Cake.Issues.Reporting.Generic addin

- input/docs/issue-providers/docfx/examples.md
> Fix DocFx examples

- input/docs/report-formats/generic/templates/htmldatatable.md
> Add link to used library

- input/docs/issue-providers/markdownlint/examples.md
Add example for markdown linting
Fixes #3
> Add example for markdown linting

- input/index.cshtml
Add linkt to start page and fix typo
> Add more links to start page

- input/docs/extending/issue-provider/rule-url-resolving.md
- input/docs/overview/features.md
- input/docs/overview/requirements.md
- input/docs/pull-request-systems/tfs/examples.md
- input/docs/report-formats/generic/examples.md
- input/docs/report-formats/generic/templates/htmldatatable.md
- input/docs/report-formats/generic/templates/htmldiagnostic.md
Otherwise entries won't be added to site TOC
> Start with H1

- GitReleaseManager.yaml
Add release date to release notes
> Add dates to release notes

- input/docs/fundamentals/architecture.md
- input/docs/overview/features.md
- input/docs/usage/creating-issues/basic-usage.md
- input/docs/usage/creating-issues/index.cshtml
- input/docs/usage/creating-reports/index.cshtml
- input/docs/usage/reading-issues/index.cshtml
- input/docs/usage/reporting-issues-to-pull-requests/index.cshtml
Add documentation for creating issues
> Add documentation for creating issues

- input/docs/report-formats/generic/templates/htmldatatable.md
Specify minium required version for HtmlDataTable template
> Specify minium required version for HtmlDataTable template

- input/docs/overview/features.md
- input/docs/usage/reporting-issues-to-pull-requests/custom-issue-filter.md
Add example for custom issue filter
> Add example for custom issue filter

- input/docs/issue-providers/msbuild/features.md
MsBuild issue provider returns project as of version 0.3.1
> MsBuild issue provider returns project as of version 0.3.1

- demos/build/create-reports/create-reports-htmldxdatagrid-file-linking.cake
- demos/build/create-reports/create-reports-htmldxdatagrid.cake
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-filelinking.html
- input/docs/report-formats/generic/templates/htmldxdatagrid.md
Add documentation and demo for file linking as implemented with https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/issues/47
> Add documentation and demo for file linking

- input/docs/report-formats/generic/features.md
Add file linking to features list
> Add file linking to features list

- input/docs/usage/creating-reports/basic-usage.md
Add basic usage report how to create reports
> Add basic usage report how to create reports

- input/docs/contributing/index.cshtml
- input/docs/resources/blog-posts.md
- input/docs/resources/index.cshtml
> Add list of blog posts

- input/docs/issue-providers/docfx/features.md
- input/docs/issue-providers/eslint/features.md
- input/docs/issue-providers/inspectcode/features.md
- input/docs/issue-providers/markdownlint/features.md
- input/docs/issue-providers/msbuild/features.md
Update issue provider features for 0.4.0
> Update issue provider features for 0.4.0

- addins/Cake.Issues.DocFx.yml
- addins/Cake.Issues.EsLint.yml
- addins/Cake.Issues.InspectCode.yml
- addins/Cake.Issues.Markdownlint.yml
- addins/Cake.Issues.MsBuild.yml
- addins/Cake.Issues.PullRequests.Tfs.yml
- addins/Cake.Issues.PullRequests.yml
- addins/Cake.Issues.Reporting.Generic.yml
- addins/Cake.Issues.Reporting.yml
- addins/Cake.Issues.Testing.yml
- addins/Cake.Issues.yml
Don't use pre-releases of addins
> Don't use pre-releases of addins

- input/docs/overview/features.md
Update documentation for Cake.Issues.PullRequests 0.4.0
> Update documentation for Cake.Issues.PullRequests 0.4.0

- demos/build/read-issues/read-issues.cake
- input/docs/report-formats/generic/templates/htmldatatable-demo-default.html
- input/docs/report-formats/generic/templates/htmldiagnostic-demo-default.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-changetitle.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-columnhiding.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-default.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-disablefiltering.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-disablegrouping.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-disableheader.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-disablesearching.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-filelinking.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-grouping.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-sorting.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-carmine.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-contrast.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-contrastcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-dark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-darkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-darkmoon.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-darkviolet.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-greenmist.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-light.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-lightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialbluelight.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materiallimelight.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialorangelight.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialpurplelight.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialteallight.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-softblue.html
Update demo files for Cake.Issues 0.4.0
> Update demo files for Cake.Issues 0.4.0

- input/docs/pull-request-systems/tfs/examples/index.cshtml
- input/docs/pull-request-systems/tfs/examples/repository-information.md
- input/docs/pull-request-systems/tfs/examples/voting.md
- input/docs/report-formats/generic/examples/custom-template.md
- input/docs/report-formats/generic/examples/default-template.md
- input/docs/report-formats/generic/examples/index.cshtml
Example how to create a report using an
> Split examples into separate pages

- input/docs/report-formats/generic/templates/htmldxdatagrid.md
Add link to option enumeration value
> Add link to option enumeration value

- input/docs/extending/issue-provider/helper.md
- input/docs/extending/issue-provider/logfile-format.md
Add documentation how to implement multiple log file format support
> Add documentation how to implement multiple log file format support

- input/docs/extending/issue-provider/logfile-format.md
> Fix typo in examples

- input/docs/extending/pull-request-system/overview.md
- input/docs/overview/features.md
- input/docs/pull-request-systems/tfs/features.md
Update for pull request system capabilities introduced with 0.6.0
> Update for pull request system capabilities

- input/docs/issue-providers/markdownlint/examples.md
Update Markdownlint example to current version
> Update Markdownlint example to current version

- README.md
- addins/Cake.Issues.PullRequests.Tfs.yml
- input/docs/pull-request-systems/tfs/examples/pullrequest-id.md
- input/docs/pull-request-systems/tfs/examples/repository-information.md
- input/docs/pull-request-systems/tfs/features.md
- input/docs/pull-request-systems/tfs/index.cshtml
- input/docs/report-formats/generic/features.md
- input/index.cshtml
> Change VSTS to Azure DevOps

- input/docs/pull-request-systems/appveyor/examples/index.cshtml
- input/docs/pull-request-systems/appveyor/features.md
- input/docs/pull-request-systems/tfs/examples/index.cshtml
- input/docs/pull-request-systems/tfs/features.md
Add link to demo repositories
Fixes #86
> (GH-86) Add link to demo repositories

- input/docs/report-formats/generic/templates/htmldatatable.md
- input/docs/report-formats/generic/templates/htmldiagnostic.md
- input/docs/report-formats/generic/templates/htmldxdatagrid.md
Fix link to custom template sample
> Fix link to custom template sample

- input/docs/pull-request-systems/tfs/features.md
- input/docs/pull-request-systems/tfs/setup.md
Add instructions how to setup Cake.Issues.PullRequests.Tfs authentication
> Add instructions how to setup Cake.Issues.PullRequests.Tfs authentication

- input/docs/pull-request-systems/tfs/examples/repository-information.md
Fix link to TfsPullRequests alias
> Fix link to TfsPullRequests alias

- input/docs/pull-request-systems/tfs/examples/pullrequest-id.md
Complete sample for writing issues to TFS pullrequest using ID
> Complete sample for writing issues to TFS pullrequest using ID

- input/docs/pull-request-systems/tfs/examples/azure-pipelines.md
Add example how to use with Azure Pipelines
> Add example how to use with Azure Pipelines

- input/docs/issue-providers/docfx/examples.md
- input/docs/issue-providers/inspectcode/examples.md
- input/docs/issue-providers/markdownlint/examples.md
- input/docs/issue-providers/msbuild/examples.md
- input/docs/pull-request-systems/appveyor/examples/write-messages.md
- input/docs/pull-request-systems/tfs/examples/azure-pipelines.md
- input/docs/pull-request-systems/tfs/examples/pullrequest-id.md
- input/docs/pull-request-systems/tfs/examples/repository-information.md
- input/docs/report-formats/generic/examples/custom-template.md
- input/docs/report-formats/generic/examples/default-template.md
- input/docs/usage/creating-issues/basic-usage.md
- input/docs/usage/creating-reports/basic-usage.md
- input/docs/usage/reading-issues/basic-usage.md
- input/docs/usage/reporting-issues-to-pull-requests/basic-usage.md
- input/docs/usage/reporting-issues-to-pull-requests/custom-issue-filter.md
Add note that addins and tools should be pinned
> Add note about addin pinning

- input/docs/pull-request-systems/tfs/examples/pullrequest-id.md
- input/docs/pull-request-systems/tfs/examples/repository-information.md
Make clear that some examples are for on-premise TFS using NTLM authentication
> Make clear that some examples are for on-premise TFS

- input/docs/resources/presentations.md
Add presentation from Azure DevOps Saturday Gothenburg
> Add presentation from Azure DevOps Saturday Gothenburg

- input/docs/contributing/index.cshtml
- input/docs/extending/index.cshtml
- input/docs/fundamentals/issue-provider.md
- input/docs/fundamentals/pull-request-system.md
- input/docs/fundamentals/recipe.md
- input/docs/fundamentals/report-format.md
- input/docs/issue-providers/index.cshtml
- input/docs/overview/features.md
- input/docs/pull-request-systems/index.cshtml
- input/docs/recipe/configuration.md
- input/docs/recipe/demos.md
- input/docs/recipe/index.cshtml
- input/docs/recipe/overview.md
- input/docs/recipe/supported-tools.md
- input/docs/recipe/tasks.md
- input/docs/recipe/usage.md
- input/docs/report-formats/index.cshtml
- input/docs/usage/creating-issues/index.cshtml
- input/docs/usage/creating-reports/index.cshtml
- input/docs/usage/reading-issues/index.cshtml
- input/docs/usage/recipe/basic-usage.md
- input/docs/usage/recipe/index.cshtml
- input/docs/usage/reporting-issues-to-pull-requests/index.cshtml
Add documentation for Cake.Issues.Recipe
> Add documentation for Cake.Issues.Recipe

- input/docs/usage/recipe/basic-usage.md
Improve usage example for Cake.Issues.Recipe
> Improve usage example for Cake.Issues.Recipe

- addins/Cake.Issues.Recipe.yml
Show Cake.Issues.Recipe in addins and add release notes
> Show Cake.Issues.Recipe in addins and add release notes

- build.cake
- input/_Navbar.cshtml
Update addins and recipe version
> Update addins and recipe version

- input/docs/pull-request-systems/tfs/examples/pullrequest-id.md
Add missing link to Cake.Git package
> Add missing link to Cake.Git package

- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialbluedark.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materiallimedark.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialorangedark.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialpurpledark.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialtealdark.cake
- demos/build/create-reports/create-reports-htmldxdatagrid.cake
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialbluedark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materiallimedark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialorangedark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialpurpledark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialtealdark.html
- input/docs/report-formats/generic/templates/htmldxdatagrid.md
> Add material dark themes

- demos/build/create-reports/create-reports-htmldxdatagrid-custom-script-location.cake
- demos/build/create-reports/create-reports-htmldxdatagrid.cake
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-customscriptlocation.html
- input/docs/report-formats/generic/templates/htmldxdatagrid.md
Add sample for custom script location and version in HtmlDxDataGrid template
> Add sample for custom script location and version in HtmlDxDataGrid template

- input/docs/recipe/configuration.md
- input/docs/recipe/supported-tools.md
Add parameter for MSBuild binary log file support
> Add parameter for MSBuild binary log file support

- input/index.cshtml
Update description to current alias count of 75
> Update description to current alias count

- input/docs/issue-providers/msbuild/features.md
Add binary log file format to supported formats of MsBuild issue provider
> Add binary log file format to supported formats of MsBuild issue provider

- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialbluedarkcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialbluelightcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materiallimedarkcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materiallimelightcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialorangedarkcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialorangelightcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialpurpledarkcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialpurplelightcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialtealdarkcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid-theme-materialteallightcompact.cake
- demos/build/create-reports/create-reports-htmldxdatagrid.cake
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialbluedarkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialbluelightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materiallimedarkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materiallimelightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialorangedarkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialorangelightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialpurpledarkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialpurplelightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialtealdarkcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid-demo-theme-materialteallightcompact.html
- input/docs/report-formats/generic/templates/htmldxdatagrid.md
Add demos for HtmlDxDataGrid compact material themes
> Add demos for HtmlDxDataGrid compact material themes

- input/docs/usage/creating-reports/basic-usage.md
Fix usage example for report creation
> Fix example for report creation

- build.cake
Build with Cake.Wyam.Recipe 0.6.0
> Build with Cake.Wyam.Recipe 0.6.0

- .gitignore
- addins/Cake.Issues.GitRepository.yml
- input/docs/issue-providers/gitrepository/examples.md
- input/docs/issue-providers/gitrepository/features.md
- input/docs/issue-providers/gitrepository/index.cshtml
- input/docs/issue-providers/gitrepository/requirements.md
Add  documentation for Cake.Issues.GitRepository
> Add  documentation for Cake.Issues.GitRepository

- build.cake
Build with Cake.Wyam.Recipe 0.7.0
> Build with Cake.Wyam.Recipe 0.7.0

- input/docs/issue-providers/gitrepository/rules/BinaryFileNotTrackedByLfs.md
- input/docs/issue-providers/gitrepository/rules/index.cshtml
Add documentation for BinaryFileNotTrackedByLfs rule
Fixes #118
> (GH-118) Add documentation for Cake.Issues.GitRepository rules

- build.cake
Update Cake.Wyam.Recipe to 0.7.1
> Update Cake.Wyam.Recipe to 0.7.1

- build.cake
Update YamlDotNet to 6.1.2, Cake.FileHelpers to 3.2.0 and Git Release Manager to 0.8.0
> Update components of build script

- build.cake
Change domain name to cakeissues.net
> Change domain name to cakeissues.net

- input/docs/issue-providers/gitrepository/rules/BinaryFileNotTrackedByLfs.md
Add note that binary files are all files which are not text files
> Add note that binary files are all files which are not text files

- build.cake
Update Cake.Wyam.Recipe to 0.8.0
> Build with Cake.Wyam.Recipe 0.8.0

- input/docs/extending/issue-provider/tutorials/settings.md
- input/docs/extending/issue-provider/tutorials/simple.md
- input/docs/usage/creating-issues/basic-usage.md
- input/docs/usage/reading-issues/basic-usage.md
Update documentation for 0.8.0 release
> Update documentation for 0.8.0

- input/docs/resources/blog-posts.md
Add link to "Finding typos with ReSharper Command Line Tools, ReSpeller and Cake" blog post
> Add "Finding typos with ReSharper Command Line Tools, ReSpeller and Cake" blog post

- .gitignore
- addins/Cake.Issues.Reporting.Sarif.yml
Add Cake.Issues.Reporting.Sarif
> Add Cake.Issues.Reporting.Sarif

- input/index.cshtml
Mention SARIF support on homepage
> Mention SARIF support on homepage

- input/_Bottom.cshtml
- input/_Head.cshtml
- input/_Navbar.cshtml
- input/assets/css/override.less
Add search box based on [DocSearch](https://docsearch.algolia.com/)
> Add search box

- .gitignore
Add dupfinder documentation to gitignore
> Add dupfinder documentation to gitignore

- build.cake
Add addin name to release notes pages to improve search results
> Add addin name to release notes pages

- input/docs/usage/creating-issues/creating-issues.md
- input/docs/usage/creating-reports/creating-reports.md
- input/docs/usage/reading-issues/reading-issues.md
- input/docs/usage/recipe/using-cake-issues-recipe.md
- input/docs/usage/reporting-issues-to-pull-requests/report-issues-to-pull-requests.md
Change title for usage documentation to improve search index
> Change title for usage documentation to improve search index

- input/docs/usage/reading-issues/run-information.md
Add example how to pass additional run information while reading issues
Fixes #150
> (GH-150) Add example how to pass additional run information

- input/docs/usage/reading-issues/file-linking.md
Add example how to pass file link settings while reading issues.
Fixes #149
> (GH-149) Add example how to pass file link settings

- input/news/2020-08-22-cake-issues-v0.9.0-released.md
Fix title of blog post for Cake.Issues 0.9.0
> Fix title of blog post

- input/news/2020-09-19-cake-issues-v0.9.1-released.md
Add blog post for Cake.Issues and Cake.Issues.PullRequests.AzureDevOps 0.9.1
> Add blog post for Cake.Issues 0.9.1

- .gitignore
- addins/Cake.Issues.PullRequests.GitHubActions.yml
- input/index.cshtml
- input/news/2020-09-27-github-actions-addin.md
Add documentation and news entry for new Cake.Issues.PullRequests.GitHubActions addin
> Add documentation for Cake.Issues.PullRequests.GitHubActions

- input/docs/index.cshtml
Format contribution info as annotation:
> Format contribution info as annotation

- input/docs/thanks.cshtml
Add page for thanking contributors:
> Add contributors page

- build.cake
Update Git Release Manager to 0.11.0
> Update Git Release Manager to 0.11.0

- input/news/2020-10-20-cake-issues-msbuild-v0.9.1-released.md
Add news entry for Cake.Issues.MsBuild 0.9.1 release
> Add news entry for Cake.Issues.MsBuild 0.9.1

- input/news/2020-10-09-cake-issues-pullrequests-v0.9.1-released.md
Add news entry for Cake.Issues.PullRequests 0.9.1
> Add news entry for Cake.Issues.PullRequests 0.9.1

- input/news/2020-21-01-cake-issues-recipe-v0.4.4-released.md
Add news entry for Cake.Issues.Recipe 0.4.4
> Add news entry for Cake.Issues.Recipe 0.4.4

- input/news/2020-08-22-cake-issues-v0.9.0-released.md
- input/news/2020-09-19-cake-issues-v0.9.1-released.md
- input/news/2020-10-20-cake-issues-msbuild-v0.9.1-released.md
> Change username

- .gitignore
- addins/Cake.Issues.Terraform.yml
Add Cake.Issues.Terraform addin
> Add Cake.Issues.Terraform addin

- addins/Cake.Issues.PullRequests.yml
- addins/Cake.Issues.Reporting.yml
Update repository link for Cake.Issues.Reporting and Cake.Issues.PullRequests.
> Update repository link

- input/news/2021-07-27-terraform-addin.md
Add news entry for Cake.Issues.Terraform
> Add news entry for Cake.Issues.Terraform

- input/news/2021-07-28-cake-issues-v1.0.0-released.md
Add blog post for Cake.Issues 1.0.0
> Add blog post for Cake.Issues 1.0.0

- input/news/2021-07-30-cake-issues-eslint-v1.0.1-released.md
Add release notes for Cake.Issues.EsLint 1.0.1
> Add release notes for Cake.Issues.EsLint 1.0.1

- addins/Cake.Frosting.Issues.Recipe.yml
- addins/Cake.Issues.Recipe.yml
Add Cake.Issues.FrostingRecipe
> Add Cake.Frosting.Issues.Recipe

- input/docs/usage/recipe/using-cake-frosting-issues-recipe.md
Add example how to use Cake.Frosting.Issues.Recipe
> Add example for Cake.Frosting.Issues.Recipe

- build.cake
- build/AddinSpec.cake
Add possibility to pass additional content to release note pages
> Add possibility to pass additional content to release note pages

- addins/Cake.Frosting.Issues.Recipe.yml
- addins/Cake.Issues.Recipe.yml
Cake.Issues.Recipe and Cake.Frosting.Issues.Recipe share their lifecycle and release notes
> Remove duplicated release notes for recipes

- addins/Cake.Frosting.Issues.Recipe.yml
Add Cake.Frosting.Issues.Recipe to API documentation
> Add Cake.Frosting.Issues.Recipe to API documentation

- input/news/2021-08-04-cake-issues-recipe-v1.0.0-released.md
Add news entry for Cake.Issues recipes 1.0
> Add news entry for Cake.Issues recipes 1.0

- input/news/2021-08-04-cake-issues-recipe-v1.0.0-released.md
Fix link to Cake.Frosting.Issues.Recipe example
> Fix link to Cake.Frosting.Issues.Recipe example

- input/docs/overview/introduction.md
Mention recipe scripts in introduction
> Mention recipe scripts in introduction

- input/news/2021-08-11-cake-issues-recipe-v1.1.0-released.md
Add news entry for Cake.Issues recipes 1.1.0 release
> Add news entry for Cake.Issues recipes 1.1.0 release

- addins/Cake.Issues.Reporting.Console.yml
Add Cake.Issues.Reporting.Console addin
> Add Cake.Issues.Reporting.Console addin

- input/news/2021-08-19-cake-issues-recipe-v1.2.0-released.md
Add news entry for Cake Issues Recipes v1.2.0
> Add news entry for Cake Issues Recipes v1.2.0

- input/news/2021-08-19-cake-issues-recipe-v1.2.0-released.md
> Fix heading in news entry

- input/news/2021-08-31-cake-issues-markdownlint-v1.1.0.md
Add news entry for Cake.Issues.Markdownlint 1.1.0
> Add news entry for Cake.Issues.Markdownlint 1.1.0

- .gitignore
- build.cake
- config.wyam
- input/docs/contributing/git-issues.cshtml
- input/docs/contributing/how-to-build.md
- input/docs/contributing/how-to-release.md
- input/docs/contributing/issues.cshtml
I missed the hacktoberfest for this issue, I'm sorry, that it took longer. But here is my proposal.
As talked about, the list is "here" /docs/contributing/git-issues
You can change the label in the build.cake-file
Solves #129
> Overview of open issues with specified label

- input/news/2022-12-10-cake-issues-v2.0.0-released.md
Add news entry for Cake.Issues 2.0 release
> Add news entry for Cake.Issues 2.0

- input/news/2023-07-22-cake-issues-v3.0.0-released.md
Adds news entry for Cake.Issues 3.0
> Add news entry for Cake Issues 3.0

- .config/dotnet-tools.json
- build.cake
- build/addins.cake
Build with Cake 2.0.0 using Cake.Wyam.Recipe 2.0.0
> Build with Cake 2.0.0 using Cake.Wyam.Recipe 2.0.0

- build.cake
Consume KuduSync global tool from Azure Artifacts, since MyGet.org is currently down
> Consume KuduSync global tool from Azure Artifacts

- input/news/2023-08-16-cake-issues-recipe-v3.1.0-released.md
Adds a news entry for the release of Cake.Issues.Recipe 3.1.0
> Add news entry for Cake.Issues.Recipe 3.1.0

- appveyor.yml
Make .NET Core 2.1 available on CI server
> Make .NET Core 2.1 available on CI server
